language: java

jdk:
  - oraclejdk8
env:
  - ORG_GRADLE_PROJECT_sonatypeUser=dummy ORG_GRADLE_PROJECT_sonatypePassword=dummy TERM=dumb

sudo: false

after_success:
  - gradle jacocoTestReport coveralls
